baseURL: "https://acardenasj-blogdown1.netlify.app"
title: Aprendiendo Blogdown desde cero
theme: hugo-theme-m10c
paginate: 5
menu:
  main:
    - identifier: home
      name: Inicio
      url: /
      weight: 1
    - identifier: tags
      name: Enlaces
      url: /tags/
      weight: 2
    - identifier: about
      name: Sobre mí
      url: /about/
      weight: 3
params:
  author: Ariana Cardenas
  description: Este blog está pensado para mostrar el paso a paso de crear webs usando Blogdown.
  menu_item_separator: ' - '
  avatar: "/ARIANAC.jpg"
  social:
    - icon: github
      name: Github
      url: https://github.com/ArianaCardenas/BlogdownR
    - icon: twitter
      name: Twitter
      url: https://twitter.com/ArianaCrdenas7
    - icon: linkedin
      name: Linkedin
      url: https://www.linkedin.com/in/ariana-cardenas/
  